Integrate ioi2017's communication task type into cms' communication task type
ioi-2022/cms pull request #20
Opened 2021-04-16 17:39 UTC by aguss787

Resolves #19 

![image](https://user-images.githubusercontent.com/9874779/115063065-45da5c00-9f15-11eb-9a6f-7d9815521079.png)

2021-04-16 18:25 UTC, aguss787 commented
Since there is a new configuration, existing problem must be re-saved to update its config

2021-04-17 07:41 UTC, fushar requested changes

2021-04-17 07:41 UTC, fushar commented on cms/grading/tasktypes/Communication.py
> -
Super duper minor nit: please revert this; I think this is CMS's style to have 2 newlines after imports

2021-04-17 07:41 UTC, fushar commented on cms/grading/tasktypes/Communication.py
> +                  and box_success_mgr and evaluation_success_mgr
Revert this change?

2021-04-17 07:41 UTC, fushar commented on cms/grading/tasktypes/Communication.py
> +            stats_user["execution_time"] >= job.time_limit:
Revert this change?

2021-04-17 10:57 UTC, aguss787 commented
Ah right, duh, auto formatting nya intellij :''

2021-04-18 15:00 UTC, fushar approved these changes

2021-04-18 15:01 UTC, merged